/****************************************************************
 LogBinomial.H
 Copyright (C)2023 William H. Majoros (bmajoros@alumni.duke.edu).
 This is OPEN SOURCE SOFTWARE governed by the Gnu General Public
 License (GPL) version 3, as described at www.opensource.org.
 ****************************************************************/
#ifndef INCL_LogBinomial_H
#define INCL_LogBinomial_H

float logBinomialProb(float p, int k, int n);

#endif
