/****************************************************************
 Trapezoids.H
 Copyright (C)2023 William H. Majoros (bmajoros@alumni.duke.edu).
 This is OPEN SOURCE SOFTWARE governed by the Gnu General Public
 License (GPL) version 3, as described at www.opensource.org.
 ****************************************************************/
#ifndef INCL_Trapezoids_H
#define INCL_Trapezoids_H

#include <vector>

std::vector<float> computeTrapezoidAreas(const std::vector<float> &);

#endif
